package core;

/**
 * Enumeration correspondante au module activable.
 * @author Groupe6
 *
 */
public enum EConfiguration {
	SERVEUR_ENREGISTREMENT,
	SERVEUR_GERER_PROFIL,
	SERVEUR_PARTAGE,
	SERVEUR_NOTIF_MAIL,
	SERVEUR_NOTIF_POPUP,
	SERVEUR_LIMITE_ESPACE,
	CLIENT_VUE_PROFIL,
	CLIENT_VUE_QUOTA,
	CLIENT_VUE_INFO_FICHIER,
	CLIENT_VUE_ARBORESCENCE,
	CLIENT_OPT_TRI,
	CLIENT_FCT_DEPLACEMENT;
}